---
title: "experimental labels"
format:
  html:
    toc: true
    toc-location: left
    number-sections: true
    self-contained: true
    output-file: "labels"
editor_options: 
  chunk_output_type: console
execute: 
  echo: true
  message: false
  warning: false
---

# Setup

```{r}
system("quarto -V")
```


```{r}
#| label: setup

source("https://inkaverse.com/setup.r")
```

## Field-book

```{r}
gs <- "https://docs.google.com/spreadsheets/d/1DxRhmFtBscdZkNRlOHaP2ZLf2yYz6IKwg1cF9elXY84/edit?gid=1390923633#gid=1390923633" %>% 
  as_sheets_id()

fb <- gs %>% 
  range_read(ss = .,sheet = "fb")

#> Google fonts: https://fonts.google.com/

font <- c("Merriweather Sans", "Permanent Marker", "Tillana")
huito_fonts(font)
```

## Labels 

```{r}
label <- fb %>%
  label_layout(size = c(5.2, 8.5)
               , border_color = "forestgreen"
               , border_width = 1.5
               ) %>%
  include_image(
    value = "https://app.untrm.edu.pe/UNTRM/assets/images/untrm.png"
    , size = c(3, 1)
    , position = c(1.7, 8)
    ) %>% 
  include_image(
    value = "https://huito.inkaverse.com/img/scale.pdf"
    , size = c(3, 1)
    , position = c(1.9, 5)
    ) %>% 
  include_barcode(
    value = "qrcode"
    , size = c(5, 5)
    , position = c(2.6, 5.1)
    ) %>% 
  include_text(value = "plots"
               , position = c(4.4, 8)
               , size = 14
               , color = "red"
               , fontface = "bold"
               , font = font[2]
               ) %>% 
  include_text(value = "Escarificacion"
               , position = c(2.7, 2.2)
               , size = 12
               , color = "blue"
               , font = font[1]
               , prefix = "Escarificacion: 
  "
               ) %>% 
  include_image(
    value = "https://huito.inkaverse.com/img/scale.pdf"
    , size = c(5, 1)
    , position = c(2.6, 0.9)
    # , opts = 'image_convert(type = "Grayscale")'
    ) 

label %>% label_print(mode = "preview")
```

```{r}
#| eval: false

label %>% 
  label_print(mode = "complete"
              , filename = "design/labels"
              , paper = c( 21, 29.8)
              , units = "cm"
              )
```

